apiVersion: v2
appVersion: 0.10.0
description: A Helm chart for Kubernetes mediaserver
name: k8s-mediaserver
type: application
version: 0.10.0
dependencies:
- name: k8s-jellyfin
  version: ^0.10.0
  repository: "file://./jellyfin/"
  condition: jellyfin.enabled
- name: k8s-jackett
  version: ^0.10.0
  repository: "file://./jackett/"
  condition: jackett.enabled
- name: k8s-plex
  version: ^0.10.0
  repository: "file://./plex/"
  condition: plex.enabled
