plex_ingress_host: k8s-plex.k8s.test
image_tag: latest
podDistribution: cluster # can be "spread" or "cluster"
#UID to run the process with
puid: 1000
# GID to run the process with
pgid: 1000
# Persistent storage selections and pathing
storage:
  customVolume: false # set to true if not using a PVC (must provide volume below)
  pvcName: mediaserver-pvc
  accessMode: ""
  size: 5Gi
  pvcStorageClass: ""
  # the path starting from the top level of the pv you're passing. If your share is server.local/share/, then tv is server.local/share/media/tv
  subPaths:
    tv: media/tv
    movies: media/movies
    config: config
  volumes: {}
  #  hostPath:
  #    path: /mnt/share
ingress:
  ingressClassName: ""
nodeSelector: {}

claim: "CHANGEME"
replicaCount: 1
container:
  image: docker.io/linuxserver/plex
  nodeSelector: {}
  port: 32400
service:
  type: ClusterIP
  port: 32400
  nodePort:
  # Defines an additional LB service, requires cloud provider service or MetalLB
  extraLBService: false
  extraLBAnnotations: {}
ingress:
  enabled: true
  annotations: {}
  tls:
    enabled: false
    secretName: ""
resources: {}
#  limits:
#    cpu: 100m
#    memory: 100Mi
#  requests:
#    cpu: 100m
#    memory: 100Mi
volume: {}
#  name: pvc-plex-config
#  storageClassName: longhorn
#  annotations: {}
#  labels: {}
#  accessModes: ReadWriteOnce
#  storage: 5Gi
#  selector: {}

